name: I cannot work workflows

on: 
  push:
    branches:
      - main

jobs:
  whatever_we_want:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout some code
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
    
      - name: Say Goodbye
        run: echo "All done"
